#!/bin/sh

args="
    --screenshots
    --effect-blur 16x8
    --indicator-radius 128
    --font Cantarell
    --clock
    --inside-color 1e1e2e66
    --inside-clear-color 1e1e2e66
    --inside-ver-color 1e1e2e66
    --inside-wrong-color 1e1e2e66
    --ring-color 74c7ec
    --line-uses-ring
    --separator-color 00000000
    --indicator-thickness 10
    --text-color aaaaaa
    --text-clear-color aaaaaa
    --text-ver-color aaaaaa
    --text-wrong-color aaaaaa
"

if [[ "$1" == "fade" ]]; then
    args="$args --fade-in 0.3"
fi

if [[ "$1" == "slow" ]]; then
    args="$args --fade-in 5 --grace 10"
fi

swaylock $args
