#!/bin/sh

args="
    --image ~/Dropbox/Media/wallpapers/sunrise-over-the-lake-picture-3840x2160_79968-mm-90.jpg
    --scaling fill
    --indicator-radius 128
    --font Cantarell
    --clock
    --inside-color 1e1e2ecc
    --inside-clear-color 1e1e2ecc
    --inside-ver-color 1e1e2ecc
    --inside-wrong-color 1e1e2ecc
    --ring-color 74c7ec
    --line-uses-ring
    --separator-color 00000000
    --indicator-thickness 10
    --text-color aaaaaa
    --text-clear-color aaaaaa
    --text-ver-color aaaaaa
    --text-wrong-color aaaaaa
"

if [[ "$1" == "fade" ]]; then
    args="$args --fade-in 0.3"
fi

if [[ "$1" == "slow" ]]; then
    args="$args --fade-in 5 --grace 30"
fi

swaylock $args
