#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Menno Finlay-Smits"
email = "hello@menno.io"

[ui]
diff-formatter = ":git"

[colors]
"diff removed token" = { fg = "bright red", underline = false }
"diff added token" = { fg = "bright green", underline = false }

[aliases]
l = ["log", "-r", '@ | trunk() | ancestors(trunk()..(visible_heads() & mine()), 2)']
ll = ["log", "-r", "ancestors(reachable(@, mutable()), 2)"]
ba = ["bookmark", "list", "--all"]
